### ISSUE TITLE
Stage 1: Pilot Program

### ISSUE THREAD

**Issue by DannyS03** [w3f/1KC#1]
Publish the following:
- [x] Program Details & Team: #4 
- [x] Documentation & Writing Style: #2
- [x] Generic Code of Conduct: #3 
- [x] Contribution Criteria and Guidelines: #6
- ~[ ] Templates: #5~
- [x] Simple Platform to present the above (turned out to just be github), as well as:
  - [x] Initial Tasks
  - [x] Associated Typeforms
  - [x] Feedback option
- [x] Jumpstart campaign through primary contributors and ambassadors
- [x] Create Project to track tasks

The project created in this repo will be used to manage the Pilot Program.

**Comment by DannyS03** [comment]
Announced and initiated
